version: '3.9'

services:
  redis:
    container_name: remi_redis
    image: redis:7.4.0
    ports:
      - "6379:6379"

  api:
    container_name: remi_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - ./:/rails:delegated
      - cache:/rails/tmp/cache
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - redis
    tty: true
    stdin_open: true
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  frontend:
    container_name: remi_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  node_modules:
  cache:
  bundle:
