# fly.toml app configuration file generated for remi-app on 2024-09-03T20:53:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remi-app'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[env]
DATABASE_URL = 'sqlite3:///data/production.sqlite3'

[[mounts]]
source = 'data'
destination = '/data'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/rails/public'
url_prefix = '/'
